backend:
  name: git-gateway
  branch: main
  login: true

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "news"
    label: "Жаңалықтар"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Тақырып", name: "title", widget: "string" }
      - { label: "Дата", name: "date", widget: "datetime" }
      - { label: "Сурет", name: "image", widget: "image" }
      - { label: "Мәтін", name: "body", widget: "markdown" }
