baseURL: "https://karakalpakvoice.org"
languageCode: "kaa"
title: "Karakalpak Voice"
theme: ""

staticDir: "static"
publishDir: "public"
contentDir: "content"

enableRobotsTXT: true
enableGitInfo: true

params:
  author: "Karakalpak Voice"
  description: "Қарақалпақ тилиндеги жаңалықлар сайты"
