baseURL: "https://karakalpakvoice.org"
languageCode: "kaa"
title: "Karakalpak Voice"
publishDir: "public"
contentDir: "content"
enableRobotsTXT: true
enableGitInfo: true
theme: "ananke"

params:
  author: "Karakalpak Voice"
  description: "Қарақалпақ тилиндеги жаңалықлар сайты"
