[build]
  command = "hugo --gc --minify"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.128.0"
  HUGO_ENV = "production"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
