toml
[build]
  publish = "."
  command = "echo 'Build complete'"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[context.production.environment]
  HUGO_VERSION = "0.74.3"
