backend:
  name: github
  repo: Karol594/karakalpakvoice-site
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "news"  # Бұл "posts" емес, "news" болуы керек!
    label: "Жаңалық"
    folder: "content/news"  # Сізде мақалалар осы жерде
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Тақырып", name: "title", widget: "string"}
      - {label: "Күні", name: "date", widget: "datetime"}
      - {label: "Мазмұны", name: "body", widget: "markdown"}
      - {label: "Сурет", name: "image", widget: "image", required: false}
