backend:
  name: github
  repo: Karol594/karakalpakvoice-site
  branch: main
  client_id: Ov23liGYlaNlzZ3niSaH

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

media_library:
  name: uploadcare
  config:
    publicKey: "demopublickey"

collections:
  - name: "blog"
    label: "Мақалалар"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Тақырып", name: "title", widget: "string" }
      - { label: "Күні", name: "date", widget: "datetime" }
      - { label: "Автор", name: "author", widget: "string" }
      - { label: "Сипаттама", name: "description", widget: "text" }
      - { label: "Басты сурет", name: "image", widget: "image", required: false }
      - { label: "Санаттар", name: "categories", widget: "list", default: ["жаңалықтар"] }
      - { label: "Тегтер", name: "tags", widget: "list", required: false }
      - { label: "Мазмұны", name: "body", widget: "markdown" }

publish_mode: editorial_workflow